/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gtaun_samp_NativeFunction */

#ifndef _Included_net_gtaun_samp_NativeFunction
#define _Included_net_gtaun_samp_NativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setServerCodepage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setServerCodepage
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getServerCodepage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getServerCodepage
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerCodepage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerCodepage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerCodepage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerCodepage
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendClientMessage
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendClientMessage
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendClientMessageToAll
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendClientMessageToAll
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendPlayerMessageToPlayer
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendPlayerMessageToPlayer
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendPlayerMessageToAll
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendPlayerMessageToAll
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendDeathMessage
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendDeathMessage
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gameTextForAll
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gameTextForAll
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gameTextForPlayer
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gameTextForPlayer
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setTimer
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_setTimer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    killTimer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_killTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getMaxPlayers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getMaxPlayers
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setGameModeText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setGameModeText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setTeamCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setTeamCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addPlayerClass
 * Signature: (IFFFFIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_addPlayerClass
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addPlayerClassEx
 * Signature: (IIFFFFIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_addPlayerClassEx
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addStaticVehicle
 * Signature: (IFFFFII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_addStaticVehicle
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addStaticVehicleEx
 * Signature: (IFFFFIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_addStaticVehicleEx
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addStaticPickup
 * Signature: (IIFFFI)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_addStaticPickup
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createPickup
 * Signature: (IIFFFI)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createPickup
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    destroyPickup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_destroyPickup
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    showNameTags
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_showNameTags
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    showPlayerMarkers
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_showPlayerMarkers
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gameModeExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gameModeExit
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setWorldTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setWorldTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getWeaponName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getWeaponName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    enableTirePopping
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_enableTirePopping
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    allowInteriorWeapons
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_allowInteriorWeapons
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setWeather
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setWeather
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setGravity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setGravity
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    allowAdminTeleport
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_allowAdminTeleport
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setDeathDropAmount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setDeathDropAmount
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createExplosion
 * Signature: (FFFIF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_createExplosion
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    enableZoneNames
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_enableZoneNames
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    usePlayerPedAnims
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_usePlayerPedAnims
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disableInteriorEnterExits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disableInteriorEnterExits
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setNameTagDrawDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setNameTagDrawDistance
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disableNameTagLOS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disableNameTagLOS
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    limitGlobalChatRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_limitGlobalChatRadius
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    limitPlayerMarkerRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_limitPlayerMarkerRadius
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    connectNPC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_connectNPC
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerNPC
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerNPC
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerAdmin
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerAdmin
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    kick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_kick
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    ban
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_ban
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    banEx
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_banEx
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    sendRconCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_sendRconCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getServerVarAsString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getServerVarAsString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getServerVarAsInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getServerVarAsInt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getServerVarAsBool
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_getServerVarAsBool
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerNetworkStats
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerNetworkStats
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getNetworkStats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getNetworkStats
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createMenu
 * Signature: (Ljava/lang/String;IFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createMenu
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    destroyMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_destroyMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addMenuItem
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_addMenuItem
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setMenuColumnHeader
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setMenuColumnHeader
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    showMenuForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_showMenuForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    hideMenuForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_hideMenuForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isValidMenu
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isValidMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disableMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disableMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disableMenuRow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disableMenuRow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerMenu
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawCreate
 * Signature: (FFLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_textDrawCreate
  (JNIEnv *, jclass, jfloat, jfloat, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawLetterSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawLetterSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawTextSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawTextSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawAlignment
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawAlignment
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawUseBox
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawUseBox
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawBoxColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawBoxColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawSetShadow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawSetShadow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawSetOutline
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawSetOutline
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawBackgroundColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawBackgroundColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawFont
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawFont
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawSetProportional
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawSetProportional
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawShowForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawShowForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawHideForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawHideForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawShowForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawShowForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawHideForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawHideForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    textDrawSetString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_textDrawSetString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneCreate
 * Signature: (FFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneCreate
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneShowForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneShowForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneShowForAll
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneShowForAll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneHideForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneHideForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneHideForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneHideForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneFlashForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneFlashForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneFlashForAll
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneFlashForAll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneStopFlashForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneStopFlashForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    gangZoneStopFlashForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_gangZoneStopFlashForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    create3DTextLabel
 * Signature: (Ljava/lang/String;IFFFFIZ)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_create3DTextLabel
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jfloat, jfloat, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    delete3DTextLabel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_delete3DTextLabel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attach3DTextLabelToPlayer
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attach3DTextLabelToPlayer
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attach3DTextLabelToVehicle
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attach3DTextLabelToVehicle
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    update3DTextLabelText
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_update3DTextLabelText
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createPlayer3DTextLabel
 * Signature: (ILjava/lang/String;IFFFFIIZ)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createPlayer3DTextLabel
  (JNIEnv *, jclass, jint, jstring, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    deletePlayer3DTextLabel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_deletePlayer3DTextLabel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    updatePlayer3DTextLabelText
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_updatePlayer3DTextLabelText
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    showPlayerDialog
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_showPlayerDialog
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setSpawnInfo
 * Signature: (IIIFFFFIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setSpawnInfo
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    spawnPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_spawnPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerPosFindZ
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerPosFindZ
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerPos
 * Signature: (ILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerFacingAngle
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerFacingAngle
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerFacingAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerFacingAngle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerInRangeOfPoint
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerInRangeOfPoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerDistanceFromPoint
 * Signature: (IFFF)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerDistanceFromPoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerStreamedIn
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerStreamedIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerInterior
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerInterior
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerInterior
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerInterior
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerHealth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerHealth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerArmour
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerArmour
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerArmour
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerArmour
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerAmmo
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerAmmo
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerAmmo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerAmmo
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerWeaponState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerWeaponState
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerTeam
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerTeam
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerTeam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerTeam
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerScore
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerScore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerScore
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerScore
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerDrunkLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerDrunkLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerDrunkLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerDrunkLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerSkin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerSkin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerSkin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerSkin
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    givePlayerWeapon
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_givePlayerWeapon
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    resetPlayerWeapons
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_resetPlayerWeapons
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerArmedWeapon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerArmedWeapon
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerWeaponData
 * Signature: (IILnet/gtaun/samp/data/WeaponData;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerWeaponData
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    givePlayerMoney
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_givePlayerMoney
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    resetPlayerMoney
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_resetPlayerMoney
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerName
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerMoney
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerMoney
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerState
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerIp
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerIp
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerPing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerPing
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerWeapon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerWeapon
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerKeys
 * Signature: (ILnet/gtaun/samp/data/KeyState;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerKeys
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerTime
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerTime
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerTime
 * Signature: (ILnet/gtaun/samp/data/Time;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerTime
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    togglePlayerClock
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_togglePlayerClock
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerWeather
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerWeather
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    forceClassSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_forceClassSelection
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerWantedLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerWantedLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerWantedLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerWantedLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerFightingStyle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerFightingStyle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerFightingStyle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerFightingStyle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerVelocity
 * Signature: (ILnet/gtaun/samp/data/Velocity;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerVelocity
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    playCrimeReportForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_playCrimeReportForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerShopName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerShopName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerSkillLevel
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerSkillLevel
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerSurfingVehicleID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerSurfingVehicleID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerSurfingObjectID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerSurfingObjectID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerAttachedObject
 * Signature: (IIIIFFFFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerAttachedObject
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    removePlayerAttachedObject
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_removePlayerAttachedObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerAttachedObjectSlotUsed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerAttachedObjectSlotUsed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerChatBubble
 * Signature: (ILjava/lang/String;IFI)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerChatBubble
  (JNIEnv *, jclass, jint, jstring, jint, jfloat, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    putPlayerInVehicle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_putPlayerInVehicle
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerVehicleID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerVehicleID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerVehicleSeat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerVehicleSeat
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    removePlayerFromVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_removePlayerFromVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    togglePlayerControllable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_togglePlayerControllable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    playerPlaySound
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_playerPlaySound
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    applyAnimation
 * Signature: (ILjava/lang/String;Ljava/lang/String;FIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_applyAnimation
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    clearAnimations
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_clearAnimations
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerAnimationIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerAnimationIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getAnimationName
 * Signature: (ILjava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getAnimationName
  (JNIEnv *, jclass, jint, jstring, jint, jstring, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerSpecialAction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerSpecialAction
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerSpecialAction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerSpecialAction
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerCheckpoint
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerCheckpoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disablePlayerCheckpoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disablePlayerCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerRaceCheckpoint
 * Signature: (IIFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerRaceCheckpoint
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    disablePlayerRaceCheckpoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_disablePlayerRaceCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerWorldBounds
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerWorldBounds
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerMarkerForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerMarkerForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    showPlayerNameTagForPlayer
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_showPlayerNameTagForPlayer
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerMapIcon
 * Signature: (IIFFFIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerMapIcon
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    removePlayerMapIcon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_removePlayerMapIcon
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    allowPlayerTeleport
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_allowPlayerTeleport
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerCameraPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerCameraPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerCameraLookAt
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerCameraLookAt
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setCameraBehindPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setCameraBehindPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerCameraPos
 * Signature: (ILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerCameraPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerCameraFrontVector
 * Signature: (ILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerCameraFrontVector
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerCameraMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerCameraMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerInVehicle
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerInVehicle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerInAnyVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerInAnyVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerInCheckpoint
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerInCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isPlayerInRaceCheckpoint
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isPlayerInRaceCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerVirtualWorld
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerVirtualWorld
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerVirtualWorld
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerVirtualWorld
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    enableStuntBonusForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_enableStuntBonusForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    enableStuntBonusForAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_enableStuntBonusForAll
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    togglePlayerSpectating
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_togglePlayerSpectating
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    playerSpectatePlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_playerSpectatePlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    playerSpectateVehicle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_playerSpectateVehicle
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    startRecordingPlayerData
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_startRecordingPlayerData
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    stopRecordingPlayerData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_stopRecordingPlayerData
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createVehicle
 * Signature: (IFFFFIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createVehicle
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    destroyVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_destroyVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isVehicleStreamedIn
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isVehicleStreamedIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehiclePos
 * Signature: (ILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getVehiclePos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehiclePos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehiclePos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleZAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleZAngle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleRotationQuat
 * Signature: (ILnet/gtaun/samp/data/Quaternions;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleRotationQuat
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleDistanceFromPoint
 * Signature: (IFFF)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleDistanceFromPoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleZAngle
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleZAngle
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleParamsForPlayer
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleParamsForPlayer
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    manualVehicleEngineAndLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_manualVehicleEngineAndLights
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleParamsEx
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleParamsEx
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleParamsEx
 * Signature: (ILnet/gtaun/samp/VehicleParam;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleParamsEx
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleToRespawn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleToRespawn
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    linkVehicleToInterior
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_linkVehicleToInterior
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    addVehicleComponent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_addVehicleComponent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    removeVehicleComponent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_removeVehicleComponent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    changeVehicleColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_changeVehicleColor
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    changeVehiclePaintjob
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_changeVehiclePaintjob
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleHealth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleHealth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attachTrailerToVehicle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attachTrailerToVehicle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    detachTrailerFromVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_detachTrailerFromVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isTrailerAttachedToVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isTrailerAttachedToVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleTrailer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleTrailer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleNumberPlate
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleNumberPlate
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleComponentInSlot
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleComponentInSlot
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleComponentType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleComponentType
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    repairVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_repairVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleVelocity
 * Signature: (ILnet/gtaun/samp/data/Velocity;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleVelocity
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleAngularVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleAngularVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleDamageStatus
 * Signature: (ILnet/gtaun/samp/VehicleDamage;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleDamageStatus
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    updateVehicleDamageStatus
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_updateVehicleDamageStatus
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setVehicleVirtualWorld
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setVehicleVirtualWorld
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getVehicleVirtualWorld
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_getVehicleVirtualWorld
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createObject
 * Signature: (IFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createObject
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attachObjectToVehicle
 * Signature: (IIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attachObjectToVehicle
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setObjectPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setObjectPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getObjectPos
 * Signature: (ILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getObjectPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setObjectRot
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setObjectRot
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getObjectRot
 * Signature: (ILnet/gtaun/samp/data/PointRot;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getObjectRot
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isValidObject
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isValidObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    destroyObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_destroyObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    moveObject
 * Signature: (IFFFF)V
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_moveObject
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    stopObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_stopObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    createPlayerObject
 * Signature: (IIFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_samp_NativeFunction_createPlayerObject
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerObjectPos
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerObjectPos
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerObjectPos
 * Signature: (IILnet/gtaun/samp/data/Point;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerObjectPos
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    setPlayerObjectRot
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_setPlayerObjectRot
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    getPlayerObjectRot
 * Signature: (IILnet/gtaun/samp/data/PointRot;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_getPlayerObjectRot
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    isValidPlayerObject
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_samp_NativeFunction_isValidPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    destroyPlayerObject
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_destroyPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    movePlayerObject
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_movePlayerObject
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    stopPlayerObject
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_stopPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attachObjectToPlayer
 * Signature: (IIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attachObjectToPlayer
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_samp_NativeFunction
 * Method:    attachPlayerObjectToPlayer
 * Signature: (IIIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_samp_NativeFunction_attachPlayerObjectToPlayer
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
